apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: shay-cluster-1
  region: eu-west-1
nodeGroups:
  - name: worker-group
    instanceType: t2.micro
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
