apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: phpmyadmin
      name: phpmyadmin
    spec:
      ports:
        - name: "8001"
          port: 8001
          targetPort: 80
      selector:
        io.kompose.service: phpmyadmin
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: www
      name: www
    spec:
      type: LoadBalancer
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: www
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.network/default: "true"
            io.kompose.service: db
        spec:
          containers:
            - args:
                - --default-authentication-plugin=mysql_native_password
              env:
                - name: MYSQL_DATABASE
                  value: vapi
                - name: MYSQL_PASSWORD
                  value: vapi123456
                - name: MYSQL_ROOT_PASSWORD
                  value: vapi123456
                - name: MYSQL_USER
                  value: vapi
              image: mysql:8.0
              name: db
              ports:
                - containerPort: 3306
              resources: {}
              volumeMounts:
                - mountPath: /docker-entrypoint-initdb.d
                  name: db-hostpath0
                - mountPath: /etc/mysql/conf.d
                  name: db-hostpath1
                - mountPath: /var/lib/mysql
                  name: persistent
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/rdadmin/Tools/vapi/database
              name: db-hostpath0
            - hostPath:
                path: /home/rdadmin/Tools/vapi/conf
              name: db-hostpath1
            - hostPath:
                path: /home/rdadmin/Tools/vapi/persistent
              name: persistent
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: default
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/default: "true"
      podSelector:
        matchLabels:
          io.kompose.network/default: "true"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: phpmyadmin
      name: phpmyadmin
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: phpmyadmin
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.service: phpmyadmin
        spec:
          containers:
            - env:
                - name: MYSQL_PASSWORD
                  value: test
                - name: MYSQL_ROOT_PASSWORD
                  value: test
                - name: MYSQL_USER
                  value: user
              image: phpmyadmin/phpmyadmin
              name: phpmyadmin
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: www
      name: www
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: www
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath -o vapi-deploy.yml
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.network/default: "true"
            io.kompose.service: www
        spec:
          containers:
            - env:
                - name: APP_DEBUG
                  value: "true"
                - name: APP_ENV
                  value: local
                - name: APP_KEY
                  value: 'base64:JUXTsCKQubRlvxGv6sVwkFL2rJ/gSksD4B/68948Mww:'
                - name: APP_NAME
                  value: Laravel
                - name: APP_URL
                  value: http://vapi.test
                - name: AWS_DEFAULT_REGION
                  value: eu-west-1
                - name: AWS_USE_PATH_STYLE_ENDPOINT
                  value: "false"
                - name: BROADCAST_DRIVER
                  value: log
                - name: CACHE_DRIVER
                  value: file
                - name: DB_CONNECTION
                  value: mysql
                - name: DB_DATABASE
                  value: vapi
                - name: DB_HOST
                  value: db
                - name: DB_PASSWORD
                  value: vapi123456
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: root
                - name: FILESYSTEM_DRIVER
                  value: local
                - name: LOG_CHANNEL
                  value: errorlog
                - name: LOG_LEVEL
                  value: debug
                - name: MAIL_ENCRYPTION
                - name: MAIL_FROM_ADDRESS
                - name: MAIL_FROM_NAME
                - name: MAIL_HOST
                  value: mailhog
                - name: MAIL_MAILER
                  value: smtp
                - name: MAIL_PASSWORD
                - name: MAIL_PORT
                  value: "1025"
                - name: MAIL_USERNAME
                - name: MEMCACHED_HOST
                  value: 127.0.0.1
                - name: MIX_PUSHER_APP_CLUSTER
                - name: MIX_PUSHER_APP_KEY
                - name: PUSHER_APP_CLUSTER
                  value: mt1
                - name: QUEUE_CONNECTION
                  value: sync
                - name: REDIS_HOST
                  value: 127.0.0.1
                - name: REDIS_PASSWORD
                - name: REDIS_PORT
                  value: "6379"
                - name: SERVER_PORT
                  value: "80"
                - name: SESSION_DRIVER
                  value: file
                - name: SESSION_LIFETIME
                  value: "120"
              image: 384503189380.dkr.ecr.eu-west-1.amazonaws.com/shay-repo:vapi_www 
              name: www
              ports:
                - containerPort: 80
              resources: {}
              volumeMounts:
                - mountPath: /var/www/html/vapi
                  name: www-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/rdadmin/Tools/vapi/vapi
              name: www-hostpath0
    status: {}
kind: List
metadata: {}

